name: gohunt
description: >-
  GoHunt este o aplicație de tip treasure hunt în care utilizatorii scanează coduri
  ascunse în oraș pe baza unor indicii. Acest proiect este construit în Flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
