// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0P8Di69YtGiZiWHwJoYioxB7PDC7Mxm8',
    appId: '1:833497730250:android:e07d82dceb437284a67833',
    messagingSenderId: '833497730250',
    projectId: 'gohunt-a6d73',
    storageBucket: 'gohunt-a6d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LJkPCjF-f0uSJ1c_llwkukfiG-Qfesg',
    appId: '1:833497730250:ios:dc15c9208fc683d9a67833',
    messagingSenderId: '833497730250',
    projectId: 'gohunt-a6d73',
    storageBucket: 'gohunt-a6d73.firebasestorage.app',
    androidClientId: '833497730250-p9eho2k4ggup3s60cjamslckcqmum59v.apps.googleusercontent.com',
    iosClientId: '833497730250-b2rptmadaiah6296dsinm6q2fpubocpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gohunt',
  );

}